package View;

import Controller.MenuController;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ghedyvan
 */
public class Menu extends javax.swing.JFrame {
    
    private final MenuController controller;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.controller = new MenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelGradiente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        CadastroMenu = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenuItem();
        MenuServiço = new javax.swing.JMenuItem();
        CadastroMenu1 = new javax.swing.JMenu();
        MenuCliente1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(430, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("ADICIONAR SERVIÇO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 180, 40));

        jButton1.setText("CRIAR USUÁRIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 180, 40));

        jButton2.setText("AGENDAMENTOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEJA BEM VINDO!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelGradiente.setIcon(new javax.swing.ImageIcon("/Users/ghedyvan/Downloads/D_NQ_NP_741947-MLB42158299867_062020-O.jpg")); // NOI18N
        getContentPane().add(jLabelGradiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 520, 520));

        CadastroMenu.setText("Cadastro");

        MenuCliente.setIcon(new javax.swing.ImageIcon("/Users/ghedyvan/Documents/Imagens/Icones/cliente-icon.png")); // NOI18N
        MenuCliente.setText("Cliente");
        CadastroMenu.add(MenuCliente);

        MenuServiço.setIcon(new javax.swing.ImageIcon("/Users/ghedyvan/Documents/Imagens/Icones/tesoura-icon.png")); // NOI18N
        MenuServiço.setText("Serviço");
        CadastroMenu.add(MenuServiço);

        jMenuBar1.add(CadastroMenu);

        CadastroMenu1.setText("Operação");

        MenuCliente1.setIcon(new javax.swing.ImageIcon("/Users/ghedyvan/Documents/Imagens/Icones/cliente-icon.png")); // NOI18N
        MenuCliente1.setText("Agenda");
        MenuCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCliente1ActionPerformed(evt);
            }
        });
        CadastroMenu1.add(MenuCliente1);

        jMenuBar1.add(CadastroMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCliente1ActionPerformed
        // TODO add your handling code here:
        //this.controller.navegarAgenda();
        this.controller.navegarAgenda();
    }//GEN-LAST:event_MenuCliente1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //this.controller.navegarAgenda();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.controller.navegarAgenda();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CadastroMenu;
    private javax.swing.JMenu CadastroMenu1;
    private javax.swing.JMenuItem MenuCliente;
    private javax.swing.JMenuItem MenuCliente1;
    private javax.swing.JMenuItem MenuServiço;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGradiente;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
